### ISSUE TITLE
Ambiguous or unknown reference to RLProxy

### ISSUE THREAD

**Issue by bbarker** [ajnsit/purescript-concur-formless#1]
When trying to build [metajelo-ui](https://github.com/labordynamicsinstitute/metajelo-ui/tree/37cd445a5c03cc04c20f7f221c9ebd72103c6f4b) using spago (`npm install; cd app, npm run prod`), I get this error:

```
Error found:
in module Formless.Internal.Transform
at .spago/concur-formless/master/src/Formless/Internal/Transform.purs:20:18 - 20:29 (line 20, column 18 - line 20, column 29)

  Cannot import type RLProxy from module Type.Row
  It either does not exist or the module does not export it.
```

This seems to be an issue with Formless itself, and with some libraries I'm not yet familiar with.

**Comment by ajnsit** [comment]
Thanks for reporting this! Looks like `typelevel-prelude`'s latest version removed the re-export of `RLProxy` from `prelude`. I should have imported it from the prelude to begin with. This should fix the issue in a backward compatible way.

**Comment by ajnsit** [comment]
Related to a similar issue with halogen-formless - https://github.com/thomashoneyman/purescript-halogen-formless/pull/50.

**Comment by bbarker** [comment]
Great! :fireworks:
